### ISSUE TITLE
How can I install DCOL

### ISSUE THREAD

**Issue by BolunDai0216** [kevin-tracy/DCOL.jl#7]
Hi,

I was trying out the repo and I am new to Julia. One issue I got was not being able to install DCOL. It shows that DCOL is not in the Julia registry. Would it be possible to add some instructions on how to install it? 

Should I simply replace `DCOL` with `DifferentiableCollisions`?

Thanks in advance!

**Comment by kevin-tracy** [comment]
Yes, thank you for catching this. I just updated all the examples and bumped the version. Let me know if you still have trouble with anything.
